export const MOVIE_LIST = {
    MOVIE_LIST_START: 'MOVIE_LIST_START',
    MOVIE_LIST_SUCCESS: 'MOVIE_LIST_SUCCESS',
    MOVIE_LIST_FAILURE: 'MOVIE_LIST_FAILURE',
};
export const POPULAR_MOVIE_LIST = {
    POPULAR_MOVIE_LIST_START: 'POPULAR_MOVIE_LIST_START',
    POPULAR_MOVIE_LIST_SUCCESS: 'POPULAR_MOVIE_LIST_SUCCESS',
    POPULAR_MOVIE_LIST_FAILURE: 'POPULAR_MOVIE_LIST_FAILURE',
};
export const TOP_RATED_MOVIE_LIST = {
    TOP_RATED_MOVIE_LIST_START: 'TOP_RATED_MOVIE_LIST_START',
    TOP_RATED_MOVIE_LIST_SUCCESS: 'TOP_RATED_MOVIE_LIST_SUCCESS',
    TOP_RATED_MOVIE_LIST_FAILURE: 'TOP_RATED_MOVIE_LIST_FAILURE',
};
export const UP_COMING_MOVIE_LIST = {
    UP_COMING_MOVIE_LIST_START: 'UP_COMING_MOVIE_LIST_START',
    UP_COMING_MOVIE_LIST_SUCCESS: 'UP_COMING_MOVIE_LIST_SUCCESS',
    UP_COMING_MOVIE_LIST_FAILURE: 'UP_COMING_MOVIE_LIST_FAILURE',
};
export const MOVIE_DETAIL = {
    MOVIE_DETAIL_START: 'MOVIE_DETAIL_START',
    MOVIE_DETAIL_SUCCESS: 'MOVIE_DETAIL_SUCCESS',
    MOVIE_DETAIL_FAILURE: 'MOVIE_DETAIL_FAILURE',
};
export const SIMILAR_MOVIE = {
    SIMILAR_MOVIE_START: 'SIMILAR_MOVIE_START',
    SIMILAR_MOVIE_SUCCESS: 'SIMILAR_MOVIE_SUCCESS',
    SIMILAR_MOVIE_FAILURE: 'SIMILAR_MOVIE_FAILURE',
};