export const MOVIE_LIST = {
    START: 'MOVIE_LIST_START',
    SUCCESS: 'MOVIE_LIST_SUCCESS',
    FAILURE: 'MOVIE_LIST_FAILURE',
};
export const POPULAR_MOVIE_LIST = {
    START: 'POPULAR_MOVIE_LIST_START',
    SUCCESS: 'POPULAR_MOVIE_LIST_SUCCESS',
    FAILURE: 'POPULAR_MOVIE_LIST_FAILURE',
};
export const TOP_RATED_MOVIE_LIST = {
    START: 'TOP_RATED_MOVIE_LIST_START',
    SUCCESS: 'TOP_RATED_MOVIE_LIST_SUCCESS',
    FAILURE: 'TOP_RATED_MOVIE_LIST_FAILURE',
};
export const UP_COMING_MOVIE_LIST = {
    START: 'UP_COMING_MOVIE_LIST_START',
    SUCCESS: 'UP_COMING_MOVIE_LIST_SUCCESS',
    FAILURE: 'UP_COMING_MOVIE_LIST_FAILURE',
};
export const MOVIE_DETAIL = {
    START: 'MOVIE_DETAIL_START',
    SUCCESS: 'MOVIE_DETAIL_SUCCESS',
    FAILURE: 'MOVIE_DETAIL_FAILURE',
};
export const SIMILAR_MOVIE = {
    START: 'SIMILAR_MOVIE_START',
    SUCCESS: 'SIMILAR_MOVIE_SUCCESS',
    FAILURE: 'SIMILAR_MOVIE_FAILURE',
};