export const AppString = {
  MOVIE: 'Movie',
  TV_SERIES: 'TV Series',
  CELEBRITIES: 'Celebrities',
  NOW_PLAYING: 'No Playing',
  POPULAR: 'Popular',
  TOP_RATED: 'Top Rated',
  UP_COMING: 'Up Coming',
  AIRING_TODAY: 'Airing Today',
  ON_THE_AIR: 'On Thing Air',
  TRENDING: 'Trending',
  RELEASE_DATE: 'Release Date',
  DESCRIPTION: 'Description',
  DURATION: 'Duration',
  RATING: 'Rating',
  NUMBER_OF_EPISODE: 'Number Of Episode',
  LANGUAGE: 'Language',
  SIMILAR: 'Similar',
  ARTIST: 'Artist',
  MIN: 'min',
  TITLE: 'Remove Favorite',
  MESSAGE: 'Are you want to remove this item?',
  ARTIST_TV_SERIES_AND_MOVIES: 'Artist Movies & Tv Series',
};
